kind: Service
apiVersion: v1
metadata:
  name: hacdias-filemanager
spec:
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30002
      name: http
  type: NodePort
  selector:
    component: hacdias-filemanager
