kind: ReplicationController
apiVersion: v1
metadata:
  name: hacdias-filemanager
spec:
  replicas: 1
  selector:
    component: hacdias-filemanager
  template:
    metadata:
      labels:
        component: hacdias-filemanager
    spec:
      containers:
        - name: hacdias-filemanager
          image: hacdias/filemanager
          ports:
            - containerPort: 2000
          args : 
            [--port, "2000",--scope, "/"] 
          volumeMounts:
            - mountPath: /hostfolder
              name: hostfolder-volume
      volumes:
        - name: hostfolder-volume
          hostPath:
            # directory location on host
            path: /tmp
            #  this field is optional
            type: DirectoryOrCreate
