kind: ReplicationController
apiVersion: v1
metadata:
  name: spark-worker-2-1-2
spec:
  replicas: 1
  selector:
    component: spark-worker-2-1-2
  template:
    metadata:
      labels:
        component: spark-worker-2-1-2
    spec:
      containers:
        - name: spark-worker-2-1-2
          image: faruk/docker-spark-w-2.1.2-h2.6
          ports:
            - containerPort: 7077
            - containerPort: 8080
          command:
            - "/bin/bash"
            - "-c"
            - "--"
          args :
            - 'env && unset SPARK_MASTER_PORT && /opt/spark/sbin/start-slave.sh spark://spark-master-2-1-2:7077 && sleep infinity'
          resources:
            requests:
              cpu: 100m
 
