kind: ReplicationController
apiVersion: v1
metadata:
  name: spark-master-controller-2-1-2
spec:
  replicas: 1
  selector:
    component: spark-master-2-1-2
  template:
    metadata:
      labels:
        component: spark-master-2-1-2
    spec:
      containers:
        - name: spark-master-2-1-2
          image: faruk/kube-master-spark-2.1.2-h2.6
          ports:
            - containerPort: 7077
            - containerPort: 8080
          command:
            - "/bin/bash"
            - "-c"
            - "--"
          args :
            - 'unset SPARK_MASTER_PORT && echo $(hostname -i) "spark-master-2-1-2" >> /etc/hosts && /opt/spark/sbin/start-master.sh --ip spark-master-2-1-2 --port 7077 && sleep infinity'
          resources:
            requests:
              cpu: 100m
